config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "microposts#index"
  
  #した三つはログイン機能
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  #サインアップぺージのurlを/signupにするため。なくてもよい
  get "signup", to: "users#new"

 
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  resources :microposts, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :inquiries, only: [:new, :create]
  resources :rooms, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :content, presence: true, length: { maximum: 5000 }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  
  validates :content, presence: true, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  
  def self.search(search)
    if search
      Micropost.where(["content LIKE ?", "%#{search}%"])
    else
      Micropost.all
    end
  end
  
  
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :microposts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :microposts
  
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_microposts = user.microposts.count
  end

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @rooms = Room.all
    @inquiry = Inquiry.new
  end

  def create
    @rooms = Room.all
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      NotificationMailer.send_notification(@inquiry.name, @inquiry.email, @inquiry.content).deliver_later
      NotificationMailer.send_inquiry_to_user(@inquiry.name, @inquiry.email, @inquiry.content).deliver
      flash[:success] = "お問い合わせの送信に成功しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "お問い合わせの送信に失敗しました。。"
      render :new
    end
  end
  
  private
  
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :content)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :edit, :destroy]
  before_action :correct_user, only: [:edit, :destroy]
  
  def index
    @rooms = Room.all
    @micropost = current_user.microposts.build if logged_in?
    @microposts = Micropost.order(id: :desc).search(params[:search]).page(params[:page]).per(20)
  end
  
  def new
    @rooms = Room.all
    @micropost = Micropost.new
  end
  
  def create
      @rooms = Room.all
      @room = Room.find(params[:room_id])
      @micropost = current_user.microposts.build(micropost_params)
      @micropost.room = @room 
      if @micropost.save
        flash[:success] = "メッセージを投稿しました。"
        redirect_to @room
      else 
        @microposts = current_user.microposts.order(id: :desc).page(params[:page])
        flash.now[:danger] = "メッセージの投稿に失敗しました。"
        render :new
      end
  end
  
  def edit
    @rooms = Room.all
    @micropost = Micropost.find(params[:id])
  end
    
  def update
    @rooms = Room.all
    @micropost = Micropost.find(params[:id])
    if @micropost.update(micropost_params)
      flash[:success] = "メッセージは編集されました。"
      redirect_to root_url
    else
      flash.now[:danger] = "メッセージは編集されませんでした。"
      render :edit
    end
  end
    
  def destroy
    @micropost.destroy
    flash[:success] = "メッセージを削除しました。"
    redirect_back(fallback_location: root_path)
  end
  
  
  private
  
  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end
  
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
      redirect_to root_url
    end
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @rooms = Room.all
  end
  
  def show
    @rooms = Room.all
    @room = Room.find(params[:id])
    @micropost = @room.microposts.build
    @microposts = @room.microposts.order(id: :desc).page(params[:page])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
  def new
    @rooms = Room.all
  end

  def create
    @rooms = Room.all
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to root_path 
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end


  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return false
    end
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  # def index
    
  #     @micropost = current_user.microposts.build if logged_in?  # form_with 用
  #     @microposts = Micropost.order(id: :desc).page(params[:page])
   
  # end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(20)
  end

  def show
    @rooms = Room.all
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @rooms = Room.all
    @user = User.new
  end

  def create
    @rooms = Room.all
    @user = User.new(user_params)
    if @user.save
      
      flash[:success] = "ユーザー登録しました。"
      redirect_to root_path
    else
      flash.now[:danger] = "ユーザーの登録に失敗しました。"
      render :new
    end
  end
  
  def edit
    @rooms = Room.all
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url
    end
  end
  
  def update
    @rooms = Room.all
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールは編集されました。"
      redirect_to @user
    else
      flash.now[:danger] = "プロフィールは編集されませんでした。"
      render :edit
    end
    
    
  end
  
  

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :self_introduction, :image)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_helper.rb
module RoomHelper
  def sidebar_link_item(name, path)
    class_name = 'channel'
    class_name << ' active' if current_page?(path)

    content_tag :li, class:class_name do
      link_to name, path, class: 'channel_name'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/inquiries/create.html.erb
<h1>Inquirys#create</h1>
<p>Find me in app/views/inquirys/create.html.erb</p>

app/views/inquiries/new.html.erb
<div class="col-lg-7 container">
  <h1 class="text-center">お問い合わせ</h1>
  <%= form_with(model: @inquiry, local: true) do |f| %>
    <%= render "layouts/error_messages", model: f.object %>
    <div class="form-group">
      <%= f.label :name, "名前" %><span id="inquiry1">必須</span>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "メールアドレス" %><span id="inquiry1">必須</span>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :content, "内容" %><span id="inquiry1">必須</span>
      <%= f.text_area :content, class: "form-control", rows: 4 %>
    </div>
    <%= f.submit "送信", class: "btn btn-primary", :style => "float: right;" %>
  <% end %>
    
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-dark fixed-top">
    <a class="navbar-brand" href="/">e-MOVE</a>
    <% if logged_in? %>
      <div id="myicon">
        <%= link_to user_path(current_user), target: "_self" do %>
          <%if current_user.image? %>
            <%= image_tag current_user.image.url, :size => "32x32", :class => "nav-image" %>
          <% else %>
            <i class="fas fa-user-circle"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" onfocus="this.blur();">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="active dropdown">
          <a class="nav-link dropdown-toggle navbar-menu" href="#" data-toggle="dropdown">
            Coll of Duty
          </a>
          <ul class="dropdown-menu">
            <a href="/rooms/5", class="dropdown-item">CoD:WZ</a>
            <a href="/rooms/1", class="dropdown-item">CoD:MW</a>
            <a href="/rooms/2", class="dropdown-item">CoD:BO4</a>
            <a href="/rooms/3", class="dropdown-item">CoD:WWⅡ</a>
            <a href="/rooms/4", class="dropdown-item">CoD:IW</a>
            <a href="/rooms/6", class="dropdown-item">CoD:BO3</a>
          </ul>
        </li>
        <li class="active dropdown">
          <a class="nav-link dropdown-toggle navbar-menu" href="#" data-toggle="dropdown">
            Battlefield
          </a>
          <ul class="dropdown-menu">
            <a href="/rooms/7", class="dropdown-item">BFV</a>
            <a href="/rooms/8", class="dropdown-item">BF1</a>
            <a href="/rooms/9", class="dropdown-item">BF4</a>
          </ul>
        </li>
        
        <li><a href="/rooms/10", class="navbar-menu">R6S</a></li>
        <li><a href="/rooms/11", class="navbar-menu">Overwatch</a></li>
        <li><a href="/rooms/12", class="navbar-menu">Apex Legends</a></li>
        <li><a href="/rooms/13", class="navbar-menu">PUBG</a></li>
        <li><a href="/rooms/14", class="navbar-menu">荒野行動</a></li>
        <li><a href="/rooms/15", class="navbar-menu">フォートナイト</a></li>
        
        
        
        <p style="border-top: double 1px #FFFFFF; margin: 8px;"></p>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "お問い合わせ", new_inquiry_path, class: "navbar-menu" %></li>
          <li class="nav-item active"><%= link_to "ログアウト", logout_path, method: :delete, class: "navbar-menu" %></li>
        <% else %>
          <div class="nav-item dropdown"></div>
            <li class="nav-item active"><%= link_to "サインアップ", signup_path, class: "navbar-menu" %></li>
            <li class="nav-item active"><%= link_to "ログイン", login_path, class: "navbar-menu" %></li>
          </div>
        <% end %>      
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_right_sidebar.html.erb
＜CoD:WarZone　3月10日より配信中＞
<iframe width="400" height="190" style="max-width: 100%" src="https://www.youtube.com/embed/T5HAwU7CO68" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>EMove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
    <!--アイコンサイトFontAwesomeのリンク-->
    <script src="https://kit.fontawesome.com/8b526235da.js" crossorigin="anonymous"></script>　
    <script type="text/javascript" src="jquery.js"></script>
    <script type="text/javascript">
    $(function(){
        $('.sidebar1 a').each(function(){
            let href = location.href.slice(location.href.indexOf('/rooms') + 1);
            let sidebarHref = $(this).attr('href').slice($(this).attr('href').indexOf('/rooms') + 1);
            if(href === sidebarHref) {
              $(this).addClass('active');
            } else {
              $(this).removeClass('active');
            }
        });
    });
    </script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    
    <!--<div class="container-fluid">-->
      <%= render "layouts/flash_messages" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    
      <%= yield %>
    <!--</div>-->
  </body>
</html>

app/views/microposts/_microposts.html.erb
<div>
  <% microposts.each do |micropost| %>
    <div class="media border">
      <%if micropost.user.image? %>
        <div id="img">
          <%= image_tag micropost.user.image.url, :size => "48x48", :style => "border-radius: 50%;" %>
        </div>
      <% else %>
        <div id="icon1">
          <i class="fas fa-user-circle"></i>
        </div>
      <% end %>
      <div class="media-body">
        <div style="margin-top: 5px;">
          <%= link_to micropost.user.name, user_path(micropost.user) %> <span class="text-muted">・ <%= l micropost.created_at, format: :short %></span>
          <span class="text-muted" id="menu1">
            <div class="dropdown　media-body">
              <% if current_user == micropost.user %>
                <button class="btn btn-sm" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onfocus="this.blur();">
                  <i class="fas fa-chevron-down"></i>
                </button>
                <div class="dropdown-menu rounder-lg shadow" aria-labelledby="dropdownMenuButton">
                  <div class="dropdown-item"><i class="far fa-edit"></i><%= link_to "　編集", edit_micropost_path(micropost) %></div>
                  <div class="dropdown-item"><i class="far fa-trash-alt"></i><%= link_to "　削除", micropost, method: :delete, data: { confirm: "本当に削除してもよろしいですか？" } %></div>
                </div>
              <% end %>
            </div>
          </span>
        </div>
        <%= simple_format(micropost.content) %>
        <%= image_tag micropost.image.url if micropost.image? %>
      </div>
    </div>
  <% end %>
  <br>
  <%= paginate microposts %>
</div>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>

app/views/microposts/edit.html.erb
<div class="col-lg-7 container">
  <h1>編集ページ</h1>
  <%= form_with(model: @micropost, local: true) do |f| %>
    <%= render "layouts/error_messages", model: f.object %>
    <div class="form-group" >
      <%= f.text_area :content, class: "form-control", rows: 4 %>
    </div>
    <%= f.file_field :image %>
    <%= f.submit "投稿", class: "btn btn-primary", :style => "float: right;" %>
  <% end %>
</div>

app/views/microposts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 d-none d-md-block">
      <div class="sidebar_fixed">
        <%= render 'rooms/rooms', rooms: @rooms %>
      </div>
    </div>
    <div class="col-md-7", style="padding: 0;">
      <%= render "microposts/microposts", microposts: @microposts %>
    </div>
    <div class="col-md-3 right-sidebar1">
      <div class="sidebar_fixed right-sidebar2">
        <%= render "layouts/right_sidebar" %>
      </div>
    </div>
  </div>
</div>

app/views/microposts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-7 container">
      <h1>新規作成</h1>
      <%= form_with(model: @micropost, local: true) do |f| %>
        <%= hidden_field_tag :room_id, params[:room_id] %>
        <%= render "layouts/error_messages", model: f.object %>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control", rows: 4 %>
        </div>
        <%= f.file_field :image %>
        
        <%= f.submit "投稿", class: "btn btn-primary", :style => "float: right;" %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_rooms.html.erb
<ul style="padding: 8px 0 0 0; margin: 0;">　Coll of Duty
  <li class="sidebar1"><a href="/rooms/5" class="sidebar2">CoD:WZ</a></li>
  <li class="sidebar1"><a href="/rooms/1" class="sidebar2">CoD:MW</a></li>
  <li class="sidebar1"><a href="/rooms/2" class="sidebar2">CoD:BO4</a></li>
  <li class="sidebar1"><a href="/rooms/3" class="sidebar2">CoD:WWⅡ</a></li>
  <li class="sidebar1"><a href="/rooms/4" class="sidebar2">CoD:IW</a></li>
  <li class="sidebar1"><a href="/rooms/6" class="sidebar2">CoD:BO3</a></li>
</ul>
<ul style="padding: 4px 0 0 0; margin: 0;">　Battlefield
  <li class="sidebar1"><a href="/rooms/7" class="sidebar2">BFV</a></li>
  <li class="sidebar1"><a href="/rooms/8" class="sidebar2">BF1</a></li>
  <li class="sidebar1"><a href="/rooms/9" class="sidebar2">BF4</a></li>
</ul>
<ul style="padding: 0; margin: 0;">
<li class="sidebar1"><a href="/rooms/10" class="sidebar3">R6S</a></li>  
<li class="sidebar1"><a href="/rooms/15" class="sidebar3">Overwatch</a></li>  
<li class="sidebar1"><a href="/rooms/11" class="sidebar3">Apex Legends</a></li>  
<li class="sidebar1"><a href="/rooms/12" class="sidebar3">PUBG</a></li>  
<li class="sidebar1"><a href="/rooms/13" class="sidebar3">荒野行動</a></li>  
<li class="sidebar1"><a href="/rooms/14" class="sidebar3">フォートナイト</a></li>  
</ul>

app/views/rooms/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 d-none d-md-block">
      <div class="sidebar_fixed">
        <%= render 'rooms/rooms', rooms: @rooms %>
      </div>
    </div>
    <div class="col-md-7", style="padding: 0;">
      <h3 class="text-center"><%= @room.name %></h3>
      <%= link_to "新規作成", new_micropost_path(room_id: @room.id), class: "btn btn-outline-primary btn-sm", :style => "right: 15px;" %>
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= room_path(@room) %>" class="nav-link<%= "active" if current_page?(room_path(@room)) %>"></a>投稿一覧<span class="badge badge-secondary"><%= @aount_microposts %></span></a></li>
      </ul>
      <%= render "microposts/microposts", microposts: @microposts %>     
    </div>
    <div class="col-md-3 right-sidebar1">
      <div class="sidebar_fixed right-sidebar2">
        <%= render "layouts/right_sidebar" %>
      </div>
    </div>
  </div>
</div>

app/views/users/_users.htnl.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to "プロフィール", user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>プロフィールを編集</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <%= form_with(model: @user, local: true) do |f|%>
        <%= render "layouts/error_messages", model: f.object %>
        <div class="form-group">
          <%= label :name, "名前" %><span id="inquiry1">&nbsp;必須&nbsp;</span>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :self_introduction, "自己紹介" %>
          <%= f.text_area :self_introduction, class: "form-control", rows: 4 %>
        </div>
        <%= f.file_field :image %>
        <%= f.submit "保存", class: "btn btn-primary", :style => "float: right;" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render "users", users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>サインアップ</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @user, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, "名前" %><span id="inquiry1">必須</span>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email, "メールアドレス" %><span id="inquiry1">必須</span>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, "パスワード" %><span id="inquiry1">必須</span>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "確認用パスワード" %><span id="inquiry1">必須</span>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div> 
      <%= f.submit "サインアップ", class: "btn btn-primary btn-block" %>
      <% end %>
      <p><%= link_to "ログインはこちら", login_path %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 d-none d-md-block">
      <div class="sidebar_fixed">
        <%= render 'rooms/rooms', rooms: @rooms %>
      </div>
    </div>
    <div class="col-md-7", style="padding: 0;">
      <h1 class="text-center"><%= @user.name %></h1>
      <div class="media">
        <%if @user.image? %>
          <div id="profile-image1">
            <%= image_tag @user.image.url, :size => "144x144", :style => "border-radius: 50%;" %>
          </div>
          <div id="profile-image2">
            <%= image_tag @user.image.url, :size => "80x80", :style => "border-radius: 50%;" %>
          </div>
        <% else %>
        <div id="profile-icon1">
          <i class="fas fa-user-circle" style="font-size: 9rem;"></i>
        </div>
        <div id="profile-icon2">
          <i class="fas fa-user-circle" style="font-size: 5rem;"></i>
        </div>
        <% end %>
        <div class="media-body">
          <% if current_user == @user %>
           <%= link_to "プロフィールの編集", edit_user_path, class: 'btn btn-outline-primary btn-sm', :style => "position: absolute; right: 15px;" %>
          <% end %>
          <div class="self_introduction">
           <%= @user.self_introduction %>
          </div>
        </div>
      </div>
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link<%= "active" if current_page?(user_path(@user)) %>"></a>投稿一覧<span class="badge badge-secondary"></span></a></li>
      </ul>
      <%= render "microposts/microposts", microposts: @microposts %>
    </div>
    <div class="col-md-3 right-sidebar1">
      <div class="sidebar_fixed right-sidebar2">
        <%= render "layouts/right_sidebar" %>
      </div>
    </div>
  </div>
</div>





 
   